services:
  db:
    image: mysql:8.4.8
    container_name: optica_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - optica_network

  redis:
    image: redis:7.4-alpine
    container_name: optica_redis
    restart: unless-stopped
    networks:
      - optica_network

volumes:
  mysql_data:

networks:
  optica_network:
    driver: bridge
