services:
  app:
    image: ghcr.io/leafmtz/optica-app:latest
    container_name: optica_app
    restart: unless-stopped
    entrypoint: ["/var/www/html/docker/entrypoint.sh"]
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - optica_network

networks:
  optica_network:
    driver: bridge
