services:
  nginx-ssl:
    image: docker.io/library/nginx:alpine
    container_name: optica_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/ssl/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
      - .:/var/www/html:ro
    networks:
      - optica_network
    depends_on:
      app:
        condition: service_healthy

  app:
    build:
      context: .
      target: dev
    container_name: optica_app
    restart: unless-stopped
    entrypoint: ["/var/www/html/docker/entrypoint.sh"]
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - .:/var/www/html:z
    networks:
      - optica_network
    depends_on:
      - db

  db:
    image: mysql:8.4.8
    container_name: optica_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - optica_network

networks:
  optica_network:
    driver: bridge

volumes:
  mysql_data:
