apiVersion: apps/v1
kind: Deployment
metadata:
  name: optica-app
  labels:
    io.kompose.service: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.network/optica-store-optica-network: "true"
        io.kompose.service: app
    spec:
      nodeSelector:
        area: optica-guzman
      containers:
        - name: optica-app
          image: ghcr.io/leafmtz/optica-app:f6043163f290d6848590a316fb58e9b3328870fb
          imagePullPolicy: Always
          command: ["/var/www/html/docker/entrypoint.sh"]
          args:
            ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: MERCADOPAGO_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: MERCADOPAGO_PUBLIC_KEY
            - name: MERCADOPAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: MERCADOPAGO_ACCESS_TOKEN
            - name: MERCADOPAGO_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: MERCADOPAGO_WEBHOOK_SECRET
            - name: ZIPNOVA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: ZIPNOVA_API_TOKEN
            - name: ZIPNOVA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: ZIPNOVA_API_SECRET
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1100m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
      restartPolicy: Always
