apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    io.kompose.service: cache
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: cache
