apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    io.kompose.service: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.network/optica-store-optica-network: "true"
        io.kompose.service: db
    spec:
      nodeSelector:
        area: optica-guzman
      containers:
        - name: optica-db
          image: mysql:8.4.8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: optica-secrets
                  key: DB_PASSWORD
            - name: MYSQL_USER
              value: "guzman_user"
            - name: MYSQL_DATABASE
              value: "optica"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
