apiVersion: apps/v1
kind: Deployment
metadata:
  name: optica-worker
  labels:
    io.kompose.service: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      labels:
        io.kompose.network/optica-store-optica-network: "true"
        io.kompose.service: worker
    spec:
      nodeSelector:
        area: optica-guzman
      containers:
        - name: optica-worker
          image: ghcr.io/leafmtz/optica-app:latest
          imagePullPolicy: Always
          command: ["/var/www/html/docker/entrypoint.sh"]
          args:
            ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
          envFrom:
            - configMapRef:
                name: env
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      restartPolicy: Always
