name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ARN_OIDC }}
        aws-region: us-east-1 

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Test de Permisos ECR (Sin Build)
      run: |
        # 1. Intentamos iniciar una subida (esto gatilla el ecr:InitiateLayerUpload)
        # Si esto falla, el error saltará acá al instante sin esperar al build de Docker
        aws ecr initiate-layer-upload --repository-name optica-store --region us-east-1
        
        echo "¡Permisos OK! Ya podés volver a poner el docker build."

    - name: Build, tag y push a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: optica-store
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
